<?php
// This file is part of Moodle - http://moodle.org/

/**
 * Sends a signed dummy Passed/Failed callback to the local webhook endpoint.
 *
 * Usage:
 *   sudo -u www-data php local/proctorcore/cli/send_test_webhook.php \
 *     --sessionid=25 --result=passed
 *
 * @package local_proctorcore
 */

define('CLI_SCRIPT', true);

require(__DIR__ . '/../../../config.php');
require_once($CFG->libdir . '/clilib.php');
require_once($CFG->libdir . '/filelib.php');

[$options, $unrecognised] = cli_get_params([
    'help' => false,
    'sessionid' => null,
    'result' => 'passed',
    'eventid' => null,
], [
    'h' => 'help',
    's' => 'sessionid',
    'r' => 'result',
]);

if ($unrecognised) {
    cli_error('Unknown options: ' . implode(', ', $unrecognised));
}

if ($options['help'] || empty($options['sessionid'])) {
    echo "Send a signed dummy Server B result to ProctorCore.\n\n";
    echo "Options:\n";
    echo "  --sessionid=ID   Local ProctorCore session id (required)\n";
    echo "  --result=VALUE   passed or failed (default: passed)\n";
    echo "  --eventid=ID     Optional unique Server B event id\n";
    exit($options['help'] ? 0 : 1);
}

$sessionid = (int) $options['sessionid'];
$result = strtolower(trim((string) $options['result']));
if (!in_array($result, ['passed', 'failed'], true)) {
    cli_error('--result must be passed or failed.');
}

$repository = new \local_proctorcore\local\session_repository();
$session = $repository->get_by_id($sessionid);
if (empty($session->server_sessionid)) {
    cli_error('The selected session is not bound to a Server B session id.');
}

$config = (new \local_proctorcore\local\company_config_repository())
    ->get_effective_config((int) $session->companyid);
$secret = (string) $config->webhooksecret;
if ($secret === '') {
    cli_error('Configure local_proctorcore/webhooksecret first.');
}

$eventid = $options['eventid'] ?: 'EVT-TEST-' . gmdate('YmdHis') . '-' . random_string(8);
$payload = [
    'eventId' => $eventid,
    'eventType' => 'session.completed',
    'sessionId' => (string) $session->server_sessionid,
    'moodleSessionId' => (int) $session->id,
    'companyId' => (int) $session->companyid,
    'attemptId' => (int) $session->attemptid,
    'userId' => (int) $session->userid,
    'status' => 'completed',
    'result' => $result,
    'reasonCode' => 'development_test',
    'reason' => 'Dummy result generated by the ProctorCore CLI test tool.',
    'completedAt' => gmdate(DATE_ATOM),
];

$raw = json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
if ($raw === false) {
    cli_error('Could not encode the test payload.');
}
$signature = hash_hmac('sha256', $raw, $secret);
$url = (new moodle_url('/local/proctorcore/webhook.php'))->out(false);

$curl = new curl();
$curl->setHeader([
    'Accept: application/json',
    'Content-Type: application/json',
    'X-ProctorCore-Signature: sha256=' . $signature,
]);
$response = $curl->post($url, $raw, [
    'CURLOPT_CONNECTTIMEOUT' => 5,
    'CURLOPT_TIMEOUT' => 20,
]);
$info = $curl->get_info();

echo "HTTP " . (int) ($info['http_code'] ?? 0) . "\n";
echo $response . "\n";
